task: detect
mode: train
model: yolov8n.yaml
data: /content/drive/MyDrive/bacterial_colony_detection/data/processed/figshare_yolo/data.yaml
epochs: 80
imgsz: 1024
batch: 4
device: 0
workers: 2
patience: 20
project: /content/drive/MyDrive/bacterial_colony_detection/outputs/yolo_training
name: figshare_yolov8n_24class_scratch
exist_ok: true
pretrained: false
optimizer: auto
seed: 42
single_cls: false
max_det: 1000
verbose: true
plots: true
save: true
save_period: 10
val: true
