task: detect
mode: train
model: yolov8n.pt
data: /content/drive/MyDrive/bacterial_colony_detection/data/processed/figshare_yolo/data.yaml
epochs: 50
imgsz: 1024
batch: 4
device: 0
workers: 2
patience: 15
project: /content/drive/MyDrive/bacterial_colony_detection/outputs/yolo_training
name: figshare_yolov8n_baseline
exist_ok: true
pretrained: true
optimizer: auto
seed: 42
single_cls: false
verbose: true
plots: true
save: true
save_period: 10
val: true

