"""Draw Figshare colony bounding-box annotations on sample images."""

from __future__ import annotations

import argparse
import random
import sys
from pathlib import Path

import cv2
import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset-dir", required=True, type=Path, help="Figshare dataset root.")
    parser.add_argument("--split-csv", required=True, type=Path, help="Split CSV generated by create_figshare_splits.py.")
    parser.add_argument("--output-dir", required=True, type=Path, help="Directory for rendered QA images.")
    parser.add_argument("--num-samples", type=int, default=8, help="Number of images to render.")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--max-boxes",
        type=int,
        default=250,
        help="Maximum boxes to draw per image to keep dense plates readable. Use 0 to draw all boxes.",
    )
    parser.add_argument("--line-thickness", type=int, default=2, help="Bounding box line thickness.")
    return parser.parse_args()


def load_annotations(dataset_dir: Path) -> pd.DataFrame:
    path = dataset_dir / "annot_tab.csv"
    if not path.exists():
        raise FileNotFoundError(f"Missing annotation CSV: {path}")
    return pd.read_csv(path)


def choose_samples(split_df: pd.DataFrame, num_samples: int, seed: int) -> list[str]:
    image_names = sorted(split_df["image_name"].unique().tolist())
    rng = random.Random(seed)
    rng.shuffle(image_names)
    return image_names[: min(num_samples, len(image_names))]


def draw_boxes(image, boxes: pd.DataFrame, max_boxes: int, line_thickness: int):
    output = image.copy()
    draw_all = max_boxes <= 0
    draw_df = boxes if draw_all else boxes.head(max_boxes)

    for _, row in draw_df.iterrows():
        x1 = int(row["bbox_x"])
        y1 = int(row["bbox_y"])
        x2 = int(row["bbox_x"] + row["bbox_width"])
        y2 = int(row["bbox_y"] + row["bbox_height"])
        cv2.rectangle(output, (x1, y1), (x2, y2), (0, 255, 0), line_thickness)

    text = f"{len(boxes)} boxes (all shown)"
    if not draw_all and len(boxes) > max_boxes:
        text += f" (showing {max_boxes})"
    cv2.putText(output, text, (30, 60), cv2.FONT_HERSHEY_SIMPLEX, 1.8, (0, 0, 255), 4)
    return output


def resize_for_review(image, max_side: int = 1600):
    height, width = image.shape[:2]
    scale = min(max_side / max(height, width), 1.0)
    if scale == 1.0:
        return image
    return cv2.resize(image, (round(width * scale), round(height * scale)), interpolation=cv2.INTER_AREA)


def main() -> None:
    args = parse_args()
    dataset_dir = args.dataset_dir.expanduser().resolve()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    annotations = load_annotations(dataset_dir)
    split_df = pd.read_csv(args.split_csv)
    samples = choose_samples(split_df, args.num_samples, args.seed)

    for image_name in samples:
        image_path = dataset_dir / image_name
        image = cv2.imread(str(image_path), cv2.IMREAD_COLOR)
        if image is None:
            raise FileNotFoundError(f"Could not read image: {image_path}")

        boxes = annotations[annotations["image_name"] == image_name].copy()
        rendered = draw_boxes(image, boxes, args.max_boxes, args.line_thickness)
        rendered = resize_for_review(rendered)

        output_path = args.output_dir / f"{Path(image_name).stem}_boxes.jpg"
        ok = cv2.imwrite(str(output_path), rendered)
        if not ok:
            raise IOError(f"Could not save QA image: {output_path}")
        print(f"Saved {output_path} with {len(boxes)} boxes")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise
